// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhmMvGo9fFT0jE64cPXXMYfIJatsmHWI',
    appId: '1:464918807727:web:f6e8eedaca5f84833c005a',
    messagingSenderId: '464918807727',
    projectId: 'fir-crud-3e64a',
    authDomain: 'fir-crud-3e64a.firebaseapp.com',
    storageBucket: 'fir-crud-3e64a.appspot.com',
    measurementId: 'G-QP2JHX4X55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVrxR6FH2-X97bwGjEa6ouoZRwTGq97dQ',
    appId: '1:464918807727:android:6d5d79a0cd7d876a3c005a',
    messagingSenderId: '464918807727',
    projectId: 'fir-crud-3e64a',
    storageBucket: 'fir-crud-3e64a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAmf8UAPS8qahUCc2v4ok6WclbY2dlTnM',
    appId: '1:464918807727:ios:231cb6c02adfa9643c005a',
    messagingSenderId: '464918807727',
    projectId: 'fir-crud-3e64a',
    storageBucket: 'fir-crud-3e64a.appspot.com',
    iosBundleId: 'com.example.blooddonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAmf8UAPS8qahUCc2v4ok6WclbY2dlTnM',
    appId: '1:464918807727:ios:7d2ddd6b803ec37c3c005a',
    messagingSenderId: '464918807727',
    projectId: 'fir-crud-3e64a',
    storageBucket: 'fir-crud-3e64a.appspot.com',
    iosBundleId: 'com.example.blooddonation.RunnerTests',
  );
}
